[package]
authors = ["marcograss"]
description = "Download single files from online zip archives"
edition = "2021"
license-file = "LICENSE"
name = "partialzip"
repository = "https://github.com/marcograss/partialzip"
version = "0.6.5"

[dependencies]
bytesize = "1.0.0"
clap = "3.2.6"
curl = "0.4.24"
url = "2.1.0"
zip = "0.6.2"
