[package]
authors = ["marcograss"]
description = "Download single files from online zip archives"
edition = "2021"
license-file = "LICENSE"
name = "partialzip"
repository = "https://github.com/marcograss/partialzip"
version = "0.6.6"
exclude = ["/testdata"]

[dependencies]
anyhow = "1.0.61"
bytesize = "1.0.0"
clap = "3.2.6"
conv = "0.3.3"
curl = "0.4.24"
num-traits = "0.2.15"
url = "2.1.0"
zip = "0.6.2"

[dev-dependencies]
actix-files = "0.6.2"
actix-web = "4.1.0"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
