[package]
name = "partialzip"
version = "0.5.0"
authors = ["marcograss"]
description = "Download single files from online zip archives"
edition = "2021"

[dependencies]
clap = "2.33.0"
url = "2.1.0"
curl = "0.4.24"
zip = "0.5.3"
bytesize = "1.0.0"
